### ISSUE TITLE
Cannot create the portal container 'portal' when using es 5.6

### ISSUE THREAD

**Issue by dv-longinus** [exo-docker/exo-community#11]
Hi all,

I am trying to deploy the exco-community platform for my team however I am constantly facing issue.
Exo his hosted in a ubuntu server 18.04 VM hosted by proxmox 6 (linux based KVM hypervisor).
When I am trying to deploy the server using elasticsearch 5.6 (as docker container followed the steps from this page : https://www.elastic.co/guide/en/elasticsearch/reference/5.6/docker.html)

I always end up with this error message when deploying the latest version of exo cummunity 5.3 : | ERROR | Cannot create the portal container 'portal' . ServletContext: org.apache.catalina.core.ApplicationContextFacade@3377b224 [exo.kernel.container.RootContainer<Catalina-startStop-1>] 

However if I use the latest verison of es (7.3.2), it work and I can logging but exo is showing 400 error in the logs du to the standard token removed since version 6.5. 

I also try with version from 5.6 up to 6.4, I always end up with the same error.
`sudo docker run -d --restart always --name dv-exo -v exo_data:/srv/exo -v exo_logs:/var/log/exo --network exo --ip 172.16.1.30 -p 8080:8080 -e EXO_ES_EMBEDDED="false" -e EXO_ES_HOST="172.16.1.40" -e EXO_ES_INDEX_REPLICA_NB="1" -e EXO_ES_INDEX_SHARD_NB="5" -e EXO_ES_PORT="9200" -e EXO_DB_TYPE="mysql" -e EXO_DB_HOST="172.16.1.20" -e EXO_DB_PORT="3306" -e MYSQL_ROOT_PASSWORD="password" -e EXO_DB_NAME="exo" -e EXO_DB_USER="minus" -e EXO_DB_PASSWORD="password" -e EXO_PROXY_VHOST="host-hidden" -e EXO_PROXY_PORT="8080" -e EXO_JVM_SIZE_MAX="4g" -e EXO_JVM_METASPACE_SIZE_MAX="2g" -e EXO_HTTP_THREAD_MAX="400" -e EXO_HTTP_THREAD_MIN="40" -e EXO_MONGO_HOST="172.16.1.10" -e EXO_MONGO_PORT="27017" -e EXO_ADDONS_LIST="exo-jdbc-driver-mysql,exo-chat,exo-web-conferencing" -e EXO_ADDONS_REMOVE_LIST="exo-wallet,exo-perk-store,exo-kudos" exoplatform/exo-community:latest`

If I use the embedded es instead it work fine, but I face a few error :

2019-09-25 10:26:07,077 | INFO  | The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib] [o.a.catalina.core.AprLifecycleListener<main>] 

Error when trying to reach this page -> administration -> System -> monitoring
```
No route to host (Host unreachable) [o.e.portal.webui.application.GadgetUtil<http-nio-0.0.0.0-8080-exec-33>] 


	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [catalina.jar:8.5.45]


	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [catalina.jar:8.5.45]


2019-09-25 10:31:18,230 | ERROR | No route to host (Host unreachable) [o.e.portal.webui.application.GadgetUtil<http-nio-0.0.0.0-8080-exec-30>] 


	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [catalina.jar:8.5.45]


	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [catalina.jar:8.5.45]


	at org.json.JSONTokener.syntaxError(JSONTokener.java:450) ~[json-20070829.jar:na]


	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [catalina.jar:8.5.45]


	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [catalina.jar:8.5.45]


	at org.json.JSONTokener.syntaxError(JSONTokener.java:450) ~[json-20070829.jar:na]


	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [catalina.jar:8.5.45]


	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [catalina.jar:8.5.45]


2019-09-25 10:31:18,638 | ERROR | Error while rendering the porlet [o.e.w.a.p.PortletApplicationController<http-nio-0.0.0.0-8080-exec-33>] 


	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [catalina.jar:8.5.45]


	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [catalina.jar:8.5.45]


2019-09-25 10:31:18,638 | ERROR | Error while rendering the porlet [o.e.w.a.p.PortletApplicationController<http-nio-0.0.0.0-8080-exec-30>] 


	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [catalina.jar:8.5.45]


	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [catalina.jar:8.5.45]
```
some items are not correctly translated when choosing the french language :

![2019-09-25_11-34-49](https://user-images.githubusercontent.com/55789095/65593497-80be1d00-df88-11e9-8909-a07f52a80341.png)

And found this in the administration -> site -> branding (it is the same if I use the embedded database, so I guess it is a bug in the code)

![2019-09-25_11-35-31](https://user-images.githubusercontent.com/55789095/65593581-b105bb80-df88-11e9-92f1-2ed01fcb91cc.png)

any idea?

**Comment by fdrouet** [comment]
hello @dv-longinus it seems you mix several things / problems in this issue ;-)

First for your ES problem :

* keep in mind that you MUST use ES 5.6 (we are not compatible yet with newer versions)

you don't give much info about your problem (logs ...) and your provided configuration is only partial (eXo container only). Give more details (ideally a docker-compose.yml file with your full configuration to reproduce your problem would be perfect)

For your page problem : 

the page -> administration -> System -> monitoring was remove recently from the product you should remove the navigation node.

For the translation problem : 

we are currently working on translation for the final release of eXo 5.3 so that will probably be fixed in few weeks.

**Comment by fdrouet** [comment]
Please use eXo Tribe website forum to report problem : https://community.exoplatform.com/portal/intranet/forum
