### ISSUE TITLE
Chat addon doesn't seem to work properly

### ISSUE THREAD

**Issue by dr1ss** [exo-docker/exo-community#5]
Using docker-compose-chat.yml

`2018-09-03 15:08:32,464 | ERROR | An error occurs while processing 'Javascript in gatein-resources.xml' from the context 'Chat' [o.e.w.a.j.JavascriptConfigDeployer<Catalina-startStop-1>] 
java.lang.IllegalStateException: Duplicate ResourceId : SHARED/filedrop, later resource definition will be ignored
	at org.gatein.portal.controller.resource.script.ScriptGraph.addResource(ScriptGraph.java:223) ~[exo.portal.component.web.resources-5.1.0-RC10.jar:5.1.0-RC10]
	at org.exoplatform.web.application.javascript.JavascriptTask.execute(JavascriptTask.java:49) ~[exo.portal.component.web.resources-5.1.0-RC10.jar:5.1.0-RC10]
	at org.exoplatform.web.application.javascript.JavascriptConfigParser.processConfigResource(JavascriptConfigParser.java:133) ~[exo.portal.component.web.resources-5.1.0-RC10.jar:5.1.0-RC10]
	at org.exoplatform.web.application.javascript.JavascriptConfigDeployer.register(JavascriptConfigDeployer.java:94) ~[exo.portal.component.web.resources-5.1.0-RC10.jar:5.1.0-RC10]
	at org.exoplatform.web.application.javascript.JavascriptConfigDeployer.access$000(JavascriptConfigDeployer.java:42) ~[exo.portal.component.web.resources-5.1.0-RC10.jar:5.1.0-RC10]
	at org.exoplatform.web.application.javascript.JavascriptConfigDeployer$1.execute(JavascriptConfigDeployer.java:66) ~[exo.portal.component.web.resources-5.1.0-RC10.jar:5.1.0-RC10]
	at org.exoplatform.container.RootContainer.executeInitTasks(RootContainer.java:1317) [exo.kernel.container-5.1.0-RC10.jar:5.1.0-RC10]
	at org.exoplatform.container.RootContainer.createPortalContainer(RootContainer.java:780) [exo.kernel.container-5.1.0-RC10.jar:5.1.0-RC10]
	at org.exoplatform.container.RootContainer.createPortalContainers(RootContainer.java:356) [exo.kernel.container-5.1.0-RC10.jar:5.1.0-RC10]
	at org.exoplatform.platform.server.tomcat.PortalContainersCreator$1.run(PortalContainersCreator.java:52) [plf-tomcat-pc-creator-listener-5.1.0-RC10.jar:5.1.0-RC10]
	at org.exoplatform.platform.server.tomcat.PortalContainersCreator$1.run(PortalContainersCreator.java:50) [plf-tomcat-pc-creator-listener-5.1.0-RC10.jar:5.1.0-RC10]
	at org.exoplatform.commons.utils.SecurityHelper.doPrivilegedAction(SecurityHelper.java:291) [exo.kernel.commons-5.1.0-RC10.jar:5.1.0-RC10]
	at org.exoplatform.platform.server.tomcat.PortalContainersCreator.createPortalContainers(PortalContainersCreator.java:50) [plf-tomcat-pc-creator-listener-5.1.0-RC10.jar:5.1.0-RC10]
	at org.exoplatform.platform.server.tomcat.PortalContainersCreator.lifecycleEvent(PortalContainersCreator.java:39) [plf-tomcat-pc-creator-listener-5.1.0-RC10.jar:5.1.0-RC10]
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:94) [catalina.jar:8.5.30]
	at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:395) [catalina.jar:8.5.30]
	at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:339) [catalina.jar:8.5.30]
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:958) [catalina.jar:8.5.30]
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:872) [catalina.jar:8.5.30]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [catalina.jar:8.5.30]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1421) [catalina.jar:8.5.30]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1411) [catalina.jar:8.5.30]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]`

**Comment by vsellier** [comment]
Thanks @dr1ss for your feedback. 
The PR #6 is submitted and will be delivered soon.

**Comment by vsellier** [comment]
The problem is fixed. 
Please retry with the new version of the ``docker-compose-chat.yml``.
You will need to do a ``docker-compose -f docker-compose-chat.yml pull`` before to retrieve the new ``exo-community`` image.

**Comment by dr1ss** [comment]
Works like a charm now, merci mon ami...

**Comment by dr1ss** [comment]
Hmm actually there is a bug with the addon I think. The installation runs fine but after logging in we get this javascript error thrown from portal/scripts/5.1.0-RC10/SHARED/chatBundle--min.js
`
Uncaught TypeError: Cannot set property 'constants' of undefined
    at Module.<anonymous> (chatBundle--min.js:12)
    at s (chatBundle--min.js:6)
    at chatBundle--min.js:6
    at chatBundle--min.js:6
    at Object.execCb (bootstrap--min.js:27)
    at ba.check (bootstrap--min.js:18)
    at ba.<anonymous> (bootstrap--min.js:16)
    at bootstrap--min.js:6
    at bootstrap--min.js:22
    at h (bootstrap--min.js:6)
`

**Comment by vsellier** [comment]
It seems you are right.. again ! :smirk:
[A ticket](https://jira.exoplatform.org/browse/CHAT-976) was created on the bug tracker of the addon, it should be resolved very soon.

(I'm not reopening the ticket as it's a different problem and it's not related to the docker image.)
